version: '3.1'

services:
  db: # 서비스 명
    container_name: nestpgsql # container 이름
    image: postgres:latest # 사용할 이미지와 버전
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data # 현재 프로젝트에 DB 데이터 백업
